server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "https://tu-frontend.com"
              - "https://www.tu-frontend.com"
							- "http://localhost:4200"
            allowedMethods: [GET, POST, PUT, DELETE, PATCH, OPTIONS]
            allowedHeaders: "*"
            exposedHeaders: [Authorization]
            allowCredentials: false

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      routes:
        - id: auth-service
          uri: http://auth-service:8990
          predicates:
            - Path=/auth/**

        - id: auth-service-users
          uri: http://auth-service:8990
          predicates:
            - Path=/api/v1/users/**

        - id: flight-service
          uri: http://flight-service:8082
          predicates:
            - Path=/api/v1/airports/**,/api/v1/aircraft/**,/api/v1/routes/**,/api/v1/flight-templates/**,/api/v1/flight-instances/**

        - id: booking-service
          uri: http://booking-service:8083
          predicates:
            - Path=/api/v1/bookings/**,/api/v1/passengers/**

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET}

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web.reactive: WARN